# Generated by Django 3.2.6 on 2021-09-11 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='actor',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='actor',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='actor',
            name='photo',
            field=models.ImageField(null=True, upload_to='actors/'),
        ),
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='title',
            name='storyline',
            field=models.TextField(default=''),
        ),
    ]
