# Generated by Django 3.2.6 on 2021-09-11 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_auto_20210911_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='title',
            name='stars',
            field=models.ManyToManyField(related_name='filmography', to='imdb.Actor'),
        ),
        migrations.AddField(
            model_name='actor',
            name='place_of_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actors', to='imdb.place'),
        ),
    ]
